import type { Metadata } from "next";
import { Inria_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Inria_Sans({
  weight:  ["300", "400", "700"]
});

export const metadata: Metadata = {
  title: "Tech Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.className} antialiased bg-white`}
      >
        {children}
      </body>
    </html>
  );
}
